### ISSUE TITLE
Does this app support realtime collaboration like Google Keep does and other questions?

### ISSUE THREAD

**Issue by Joe23232** [CarnetApp/CarnetAndroid#117]
1. Does this app support realtime collaboration like Google Keep does?
2. Am I able to do realtime collaboration from Android to Linux and vice versa?
3. Does this use End to end encryption?

**Comment by PhieF** [comment]
Hi

There is no real time collaboration or E2EE, sorry !

**Comment by Joe23232** [comment]
Its ok
