### ISSUE TITLE
It does not connect, An error occured, check credentials

### ISSUE THREAD

**Issue by gerroon** [CarnetApp/CarnetAndroid#118]
Hi,

I have been using Canet app for a while from Fdroid. It always worked with my Nextcloud instance. I have not used it recently then I saw the app update and upgraded Now it fails to connect to my Nextcloud instance. I even wiped the app reinstalled it without much luck. 

I am using the cred method and my creds are fine, I even tried token based auth with no luck. 

I have Nextcloud app dev version but it does not recognize that.

I am not seeing any Carnet related log  in nextcloud.log and not sure if there is a way to get the app logs.

I am using Nextcliud 20 on Debian Testing, Carnet App  0.23.7, Carnet Fdroid (also tried the current.apkk from the dev's site)

My domain is like

`https://DOMAIN.COM/nextcloud`

**Comment by Shiroe93** [comment]
I have the stable app and it doesn't recognize it either and I have your exact problem with credentials 
How you manage to solve this?
