### ISSUE TITLE
Carnet Android app crashes on Note edit - /e/

### ISSUE THREAD

**Issue by moosbaue** [CarnetApp/CarnetAndroid#130]
Hi

Thank you for this great application

Though as of recent the app crashes an /e/ Android whenever I want to edit a note - sync works ok
Any hints, ideas, ...

Thank you
Kind regards
Josef

**Comment by VanackSabbadium** [comment]
> 
> 
> Hi
> 
> Which device do you have and which android version ? Thanks !
> 
> If anyone of you knows how to use adb, it would be great to send me a log...
> 
> Were you prompt to send a log by mail ?

I've got a Xiaomi Redmi Note 4X, Android version 7.1.2.

I'd be glad to help with a log, could you help me generate one?

**Comment by moosbaue** [comment]
Hi

I am on a Nexus 5x , Android 8.1.0
logcat attached
[logcat.txt](https://github.com/CarnetApp/CarnetAndroid/files/6439208/logcat.txt)

Thank you very much for your help

kind regards
Josef

**Comment by VanackSabbadium** [comment]
I managed to debug Carnet.
Here's the log.

Thanks
[Carnet log.txt](https://github.com/CarnetApp/CarnetAndroid/files/6439269/Carnet.log.txt)

**Comment by PhieF** [comment]
Did it happen after an update from /e/ ?

Seems like a crash with the android webview

**Comment by PhieF** [comment]
Currently working with /e/ to understand what's happening

**Comment by moosbaue** [comment]
Hi

So I know it was working in the beginning of April 2021
Then came the update during Aprill to e-0.15-o-20210313105776-dev-bullhead
and it did not work at the end of April. The update in May to e-0.16-o-20210505112607-dev-bullhead did not change the situation.
So most likely the issue was introduced on the update from e-0.14-o-2021012798648-dev-bullhead to e-0.15-o-20210313105776-dev-bullhead. Here are the release notes (I cannot make any sense of it): https://gitlab.e.foundation/e/os/releases/-/releases

Thank you again for your help
kind regards
Josef

**Comment by Zahrun** [comment]
Hi

It might be related to the Android WebView march bug.
A version of WebView having the bug might have been introduced in 0.15 and not updated in 0.16?
https://support.google.com/android/thread/103561027/an-update-regarding-app-crashes-and-system-webview?hl=en

Although the 0.16 releases notes say "Browser is now updated to the latest Bromite version. Kindly note that the version we used contains the patch for the recent Android Webview issue. So /e/ is not impacted!"

**Comment by moosbaue** [comment]
Hi

Just install Android System Webview 90.0.4430.91 (2021/04/226). Carnet still crashes

kind regards
Josef

**Comment by PhieF** [comment]
If you have an arm64 (most devices) can you try this specific version the /e/ team built ?
https://gitlab.e.foundation/e/apps/browser/-/jobs/166031/artifacts/raw/apks/SystemWebView_arm64.apk

**Comment by Zahrun** [comment]
So afaik, /e/ has three kinds of builds using different signature keys: **test**, **dev**, and **stable**.
I tried the apk on both my FP3 having **stable** build and my Nexus 4 having **dev** build.
I have the same error as @VanackSabbadium , and I think it is because it is a system app and it has been signed with a different key. Maybe the build is for the **test** channel.
Or it could be that we need to be root to update a system app like this ?
Or something I don't know.
@moosbaue , you said you installed System Webview 90.0.4430.91 (2021/04/26). Maybe you can shed some light on the process for us ?

**Comment by moosbaue** [comment]
I just installed it and it gave me no errors - sorry - but did not help either.
In the /e/ appstore there is a Webview 90.0.4430.210. Tried that too - normal install - you can then switch versions in dev mode - but made things worse: Mail crashed when trying to edit a message.

**Comment by PhieF** [comment]
You are right about the app signature

about /e/ version:
I've tried 0.16, and it's crashing
but
I've tried 0.17, built today or my device, it works

0.17 should be soon released

**Comment by digitalkram** [comment]
I can confirm that with /e/ OS 0.17 the crash problem is gone,

**Comment by moosbaue** [comment]
indeed issue is resolved
Thank you
