### ISSUE TITLE
White area above the first line of text and text area is movable

### ISSUE THREAD

**Issue by ChriScho91** [CarnetApp/CarnetAndroid#56]
### Steps to reproduce the error
1. Create a note in the Carnet Android app
2. Edit this note in the Nextcloud app
3. Open the note again in the Android app

**-> over the first line of text is a white area** 
![Screenshot_20190420-170939](https://user-images.githubusercontent.com/32893214/56459099-44f6aa00-638f-11e9-833b-157644b25868.png)

**-> the text area is movable**
![Screenshot_20190420-170955](https://user-images.githubusercontent.com/32893214/56459097-3c05d880-638f-11e9-9c63-134811d6931c.png)

**Comment by PhieF** [comment]
Grumpf I don't have this issue, is it still the case ?

**Comment by ChriScho91** [comment]
Yes, the error still occurs.

I have also noticed something else, but I do not know whether it is connected:
In the Android app I had a note that seemed to be completely empty when I opened it. Under Nextcloud I could open and edit the note that actually contained content already. After opening it once under Nextcloud, the content was also displayed again under Android.

**Comment by ChriScho91** [comment]
Just checked, I can't reproduce the error anymore. Therefore, I close the bug report.
