### ISSUE TITLE
Note name can't be saved 

### ISSUE THREAD

**Issue by purpleleaf** [CarnetApp/CarnetAndroid#97]
After last android update (version 0.20.0 from f-droid),  It is not more possibile create note name for new notes and change note name for already existing notes. The app report this error " note couldn't be renamed"

**Comment by ChangelinPipou** [comment]
rename from option menu crash (and doesn't rename)

**Comment by PhieF** [comment]
fixed with c96cfb3060990fd9f6cfa2eb055f4b95ecc712e7
